/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package edu.stolaf.cs.wmrserver.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum State implements org.apache.thrift.TEnum {
  PREP(0),
  RUNNING(1),
  SUCCESSFUL(2),
  FAILED(3),
  KILLED(4);

  private final int value;

  private State(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static State findByValue(int value) { 
    switch (value) {
      case 0:
        return PREP;
      case 1:
        return RUNNING;
      case 2:
        return SUCCESSFUL;
      case 3:
        return FAILED;
      case 4:
        return KILLED;
      default:
        return null;
    }
  }
}
